# Generated by Django 4.0.3 on 2022-03-16 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('naver_id', models.CharField(max_length=30)),
                ('naver_pw', models.CharField(max_length=30)),
                ('naver_cid', models.CharField(max_length=30)),
                ('naver_csec', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'user_setting',
            },
        ),
    ]
